version: "2"
linters:
  default: standard

  settings:
    errcheck:
      exclude-functions:
        - "(io.Closer).Close"
        - "(*database/sql.Rows).Close"
        - "os.Remove"
        - "(*github.com/go-telegram/bot.Bot).SendMessage"
        - "(*github.com/go-telegram/bot.Bot).SetMessageReaction"
        - "(*github.com/go-telegram/bot.Bot).AnswerCallbackQuery"
