version: 2
project_name: climber-count
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
      - README.md
      - LICENSE
dockers:
  - image_templates:
      - ghcr.io/eiri/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/eiri/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/eiri/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - ghcr.io/eiri/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/eiri/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/eiri/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/eiri/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/eiri/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/eiri/{{ .ProjectName }}:{{ .Version }}-amd64
  - name_template: ghcr.io/eiri/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/eiri/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/eiri/{{ .ProjectName }}:{{ .Version }}-amd64
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-rc"
release:
  prerelease: auto
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"
      - "^ci:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Refactorings"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
homebrew_casks:
  - name: climber-count
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taon"]
          end
    repository:
      owner: eiri
      name: homebrew-tap
      token: "{{ .Env.GH_HOMEBREW_PAT }}"
    commit_author:
      name: eiri
      email: eiri@eiri.ca
    commit_msg_template: "feat: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/eiri/climber-count"
    description: "Telegram bot to report a people count in your local bouldering gym"
    license: "MIT"
