services:
  climber-count:
    image: gcr.io/eiri/climber-count
    env_file: ".env"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./storage:/storage
