services:
  climber-count:
    # build:
    #   context: .
    # image: climber-count:local
    image: ghcr.io/eiri/climber-count:0.1.15
    env_file: ".env"
    ports:
      - "9117:9117"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
