services:
  climber-count:
    build:
      context: .
    image: climber-count:local
    env_file: ".env"
    ports:
      - "9117:9117"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
